INSERT INTO category (name)
VALUES
  ('featured'),
  ('front end'),
  ('back end'),
  ('fullstack'),
  ('vanilla'),
  ('web development'),
  ('game'),
  ('tool'),
  ('utility'),
  ('data structure and algorithm'),
  ('package'),
  ('template'),
  ('data analysis'),
  ('simulation'),
  ('machine learning');

INSERT INTO language (name)
VALUES
  ('JavaScript'),
  ('TypeScript'),
  ('Python'),
  ('MATLAB'),
  ('Mathematica'),
  ('Fortran'),
  ('SQL'),
  ('C++');

INSERT INTO tool (name)
VALUES
  ('Jest'),
  ('Babel'),
  ('Webpack'),
  ('PostCSS'),
  ('Tailwind CSS'),
  ('date-fns'),
  ('PubSubJS'),
  ('React'),
  ('Vite'),
  ('Vitest'),
  ('Testing Library'),
  ('React Router'),
  ('shadcn/ui'),
  ('Fuse.js'),
  ('Next.js'),
  ('Node.js'),
  ('PostgreSQL'),
  ('React Context API'),
  ('Express.js'),
  ('EJS'),
  ('express-validator'),
  ('Pandas'),
  ('Matplotlib'),
  ('scikit-learn'),
  ('NumPy'),
  ('Pillow'),
  ('mlxtend'),
  ('Seaborn'),
  ('TensorFlow/Keras'),
  ('OpenCV');

WITH pair (project, category) AS (
  VALUES
    ('Shopping List', 'front end'),
    ('Shopping List', 'vanilla'),
    ('Shopping List', 'web development'),
    ('Shopping List', 'tool'),
    ('Odin Recipes', 'front end'),
    ('Odin Recipes', 'vanilla'),
    ('Odin Recipes', 'web development'),
    ('Odin Landing Page', 'front end'),
    ('Odin Landing Page', 'vanilla'),
    ('Odin Landing Page', 'web development'),
    ('Rock-Paper-Scissors Game', 'front end'),
    ('Rock-Paper-Scissors Game', 'vanilla'),
    ('Rock-Paper-Scissors Game', 'web development'),
    ('Rock-Paper-Scissors Game', 'game'),
    ('Etch-A-Sketch', 'front end'),
    ('Etch-A-Sketch', 'vanilla'),
    ('Etch-A-Sketch', 'web development'),
    ('Etch-A-Sketch', 'tool'),
    ('Calculator', 'front end'),
    ('Calculator', 'vanilla'),
    ('Calculator', 'web development'),
    ('Calculator', 'tool'),
    ('Planet Table', 'front end'),
    ('Planet Table', 'vanilla'),
    ('Planet Table', 'web development'),
    ('High School Python', 'data analysis'),
    ('Sign Up Form', 'front end'),
    ('Sign Up Form', 'vanilla'),
    ('Sign Up Form', 'web development'),
    ('Admin Dashboard', 'front end'),
    ('Admin Dashboard', 'vanilla'),
    ('Admin Dashboard', 'web development'),
    ('Odin Library', 'front end'),
    ('Odin Library', 'vanilla'),
    ('Odin Library', 'web development'),
    ('Odin Library', 'tool'),
    ('Tic-Tac-Toe', 'front end'),
    ('Tic-Tac-Toe', 'vanilla'),
    ('Tic-Tac-Toe', 'web development'),
    ('Tic-Tac-Toe', 'game'),
    ('Image Carousel', 'front end'),
    ('Image Carousel', 'vanilla'),
    ('Image Carousel', 'web development'),
    ('Image Carousel', 'utility'),
    ('Image Carousel', 'package'),
    ('Recursion', 'vanilla'),
    ('Recursion', 'utility'),
    ('Recursion', 'data structure and algorithm'),
    ('Linked List', 'vanilla'),
    ('Linked List', 'utility'),
    ('Linked List', 'data structure and algorithm'),
    ('Hashmap', 'vanilla'),
    ('Hashmap', 'utility'),
    ('Hashmap', 'data structure and algorithm'),
    ('Binary Search Trees', 'featured'),
    ('Binary Search Trees', 'vanilla'),
    ('Binary Search Trees', 'utility'),
    ('Binary Search Trees', 'data structure and algorithm'),
    ('Knights Travails', 'vanilla'),
    ('Knights Travails', 'utility'),
    ('Knights Travails', 'data structure and algorithm'),
    ('JavaScript Form Validation', 'front end'),
    ('JavaScript Form Validation', 'vanilla'),
    ('JavaScript Form Validation', 'web development'),
    ('Testing Practice', 'vanilla'),
    ('Testing Practice', 'utility'),
    ('Webpack Front End Template', 'front end'),
    ('Webpack Front End Template', 'web development'),
    ('Webpack Front End Template', 'template'),
    ('Restaurant Page', 'front end'),
    ('Restaurant Page', 'vanilla'),
    ('Restaurant Page', 'web development'),
    ('To Do List', 'featured'),
    ('To Do List', 'front end'),
    ('To Do List', 'vanilla'),
    ('To Do List', 'web development'),
    ('To Do List', 'tool'),
    ('Weather App', 'featured'),
    ('Weather App', 'front end'),
    ('Weather App', 'vanilla'),
    ('Weather App', 'web development'),
    ('Weather App', 'tool'),
    ('Battleship Game', 'featured'),
    ('Battleship Game', 'front end'),
    ('Battleship Game', 'vanilla'),
    ('Battleship Game', 'web development'),
    ('Battleship Game', 'game'),
    ('FMR Analysis', 'tool'),
    ('FMR Analysis', 'data analysis'),
    ('Multiple Sphere T-Matrix', 'tool'),
    ('Multiple Sphere T-Matrix', 'data analysis'),
    ('Multiple Sphere T-Matrix', 'simulation'),
    ('Home Page', 'featured'),
    ('Home Page', 'front end'),
    ('Home Page', 'vanilla'),
    ('Home Page', 'web development'),
    ('Vite + React Template', 'front end'),
    ('Vite + React Template', 'web development'),
    ('Vite + React Template', 'template'),
    ('CV Application', 'featured'),
    ('CV Application', 'front end'),
    ('CV Application', 'web development'),
    ('CV Application', 'tool'),
    ('Pokémon Memory Card Game', 'front end'),
    ('Pokémon Memory Card Game', 'web development'),
    ('Pokémon Memory Card Game', 'game'),
    ('ShopShop', 'featured'),
    ('ShopShop', 'front end'),
    ('ShopShop', 'web development'),
    ('Next.js Dashboard App', 'fullstack'),
    ('Next.js Dashboard App', 'web development'),
    ('Next.js Dashboard App', 'tool'),
    ('Basic Informational Site', 'back end'),
    ('Basic Informational Site', 'web development'),
    ('Mini Message Board', 'fullstack'),
    ('Mini Message Board', 'web development'),
    ('Gerak Parabola', 'vanilla'),
    ('Gerak Parabola', 'simulation'),
    ('Regresi', 'data analysis'),
    ('Regresi', 'machine learning'),
    ('Klasifikasi dengan EMNIST dan Gambar Pindai', 'data analysis'),
    ('Klasifikasi dengan EMNIST dan Gambar Pindai', 'machine learning'),
    ('Prediksi Seedling', 'data analysis'),
    ('Prediksi Seedling', 'machine learning'),
    ('Klasifikasi CNN', 'data analysis'),
    ('Klasifikasi CNN', 'machine learning')
)
INSERT INTO project_category (project_id, category_id)
SELECT project.id, category.id
FROM pair
JOIN project ON project.name = pair.project
JOIN category ON category.name = pair.category
WHERE NOT EXISTS (
  SELECT 1 FROM project_category
  WHERE project_category.project_id = project.id
    AND project_category.category_id = category.id
);

WITH pair (project, language) AS (
  VALUES
    ('Shopping List', 'JavaScript'),
    ('Rock-Paper-Scissors Game', 'JavaScript'),
    ('Etch-A-Sketch', 'JavaScript'),
    ('Calculator', 'JavaScript'),
    ('High School Python', 'Python'),
    ('Odin Library', 'JavaScript'),
    ('Tic-Tac-Toe', 'JavaScript'),
    ('Image Carousel', 'JavaScript'),
    ('Recursion', 'JavaScript'),
    ('Linked List', 'JavaScript'),
    ('Hashmap', 'JavaScript'),
    ('Binary Search Trees', 'JavaScript'),
    ('Knights Travails', 'JavaScript'),
    ('JavaScript Form Validation', 'JavaScript'),
    ('Testing Practice', 'JavaScript'),
    ('Webpack Front End Template', 'JavaScript'),
    ('Restaurant Page', 'JavaScript'),
    ('To Do List', 'JavaScript'),
    ('Weather App', 'JavaScript'),
    ('Battleship Game', 'JavaScript'),
    ('FMR Analysis', 'MATLAB'),
    ('Multiple Sphere T-Matrix', 'Fortran'),
    ('Multiple Sphere T-Matrix', 'Mathematica'),
    ('Home Page', 'JavaScript'),
    ('Vite + React Template', 'JavaScript'),
    ('CV Application', 'JavaScript'),
    ('Pokémon Memory Card Game', 'JavaScript'),
    ('ShopShop', 'JavaScript'),
    ('Next.js Dashboard App', 'TypeScript'),
    ('Basic Informational Site', 'JavaScript'),
    ('Mini Message Board', 'JavaScript'),
    ('Mini Message Board', 'SQL'),
    ('Gerak Parabola', 'C++'),
    ('Regresi', 'Python'),
    ('Klasifikasi dengan EMNIST dan Gambar Pindai', 'Python'),
    ('Prediksi Seedling', 'Python'),
    ('Klasifikasi CNN', 'Python')
)
INSERT INTO project_language (project_id, language_id)
SELECT project.id, language.id
FROM pair
JOIN project ON project.name = pair.project
JOIN language ON language.name = pair.language
WHERE NOT EXISTS (
  SELECT 1 FROM project_language
  WHERE project_language.project_id = project.id
    AND project_language.language_id = language.id
);

WITH pair (project, tool) AS (
  VALUES
    ('Testing Practice', 'Jest'),
    ('Testing Practice', 'Babel'),
    ('Webpack Front End Template', 'Webpack'),
    ('Webpack Front End Template', 'Babel'),
    ('Webpack Front End Template', 'PostCSS'),
    ('Webpack Front End Template', 'Tailwind CSS'),
    ('Webpack Front End Template', 'Jest'),
    ('Restaurant Page', 'Webpack'),
    ('To Do List', 'Webpack'),
    ('To Do List', 'date-fns'),
    ('Weather App', 'Webpack'),
    ('Weather App', 'date-fns'),
    ('Battleship Game', 'Webpack'),
    ('Battleship Game', 'Jest'),
    ('Battleship Game', 'PubSubJS'),
    ('Home Page', 'Webpack'),
    ('Home Page', 'Tailwind CSS'),
    ('Home Page', 'PostCSS'),
    ('Vite + React Template', 'React'),
    ('Vite + React Template', 'Tailwind CSS'),
    ('Vite + React Template', 'Vite'),
    ('Vite + React Template', 'Vitest'),
    ('Vite + React Template', 'Testing Library'),
    ('Vite + React Template', 'React Router'),
    ('Vite + React Template', 'shadcn/ui'),
    ('CV Application', 'React'),
    ('CV Application', 'Tailwind CSS'),
    ('CV Application', 'Vite'),
    ('Pokémon Memory Card Game', 'React'),
    ('Pokémon Memory Card Game', 'Tailwind CSS'),
    ('Pokémon Memory Card Game', 'Vite'),
    ('ShopShop', 'React'),
    ('ShopShop', 'Tailwind CSS'),
    ('ShopShop', 'Vite'),
    ('ShopShop', 'Vitest'),
    ('ShopShop', 'Testing Library'),
    ('ShopShop', 'React Router'),
    ('ShopShop', 'shadcn/ui'),
    ('ShopShop', 'Fuse.js'),
    ('Next.js Dashboard App', 'React'),
    ('Next.js Dashboard App', 'Tailwind CSS'),
    ('Next.js Dashboard App', 'Next.js'),
    ('Next.js Dashboard App', 'Node.js'),
    ('Next.js Dashboard App', 'PostgreSQL'),
    ('Next.js Dashboard App', 'React Context API'),
    ('Basic Informational Site', 'Node.js'),
    ('Basic Informational Site', 'Express.js'),
    ('Mini Message Board', 'Node.js'),
    ('Mini Message Board', 'Express.js'),
    ('Mini Message Board', 'EJS'),
    ('Mini Message Board', 'PostgreSQL'),
    ('Mini Message Board', 'date-fns'),
    ('Mini Message Board', 'express-validator'),
    ('Regresi', 'Pandas'),
    ('Regresi', 'Matplotlib'),
    ('Regresi', 'scikit-learn'),
    ('Klasifikasi dengan EMNIST dan Gambar Pindai', 'NumPy'),
    ('Klasifikasi dengan EMNIST dan Gambar Pindai', 'Matplotlib'),
    ('Klasifikasi dengan EMNIST dan Gambar Pindai', 'scikit-learn'),
    ('Klasifikasi dengan EMNIST dan Gambar Pindai', 'Pillow'),
    ('Klasifikasi dengan EMNIST dan Gambar Pindai', 'mlxtend'),
    ('Prediksi Seedling', 'NumPy'),
    ('Prediksi Seedling', 'Matplotlib'),
    ('Prediksi Seedling', 'scikit-learn'),
    ('Prediksi Seedling', 'Pandas'),
    ('Prediksi Seedling', 'Seaborn'),
    ('Klasifikasi CNN', 'NumPy'),
    ('Klasifikasi CNN', 'Matplotlib'),
    ('Klasifikasi CNN', 'TensorFlow/Keras'),
    ('Klasifikasi CNN', 'OpenCV')
)
INSERT INTO project_tool (project_id, tool_id)
SELECT project.id, tool.id
FROM pair
JOIN project ON project.name = pair.project
JOIN tool ON tool.name = pair.tool
WHERE NOT EXISTS (
  SELECT 1 FROM project_tool
  WHERE project_tool.project_id = project.id
    AND project_tool.tool_id = tool.id
);
